# Generated by Django 4.2.30 on 2026-06-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_judgeresult_memory_used_alter_submission_memory_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeresult',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待判题'), ('JUDGING', '正在判题'), ('ACCEPTED', '答案正确'), ('WRONG_ANSWER', '答案错误'), ('TIME_LIMIT_EXCEEDED', '运行超时'), ('RUNTIME_ERROR', '运行错误'), ('SYSTEM_ERROR', '系统错误'), ('COMPILE_ERROR', '编译错误')], max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python3', 'Python 3'), ('c', 'C'), ('cpp', 'c++')], default='python3', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待判题'), ('JUDGING', '正在判题'), ('ACCEPTED', '答案正确'), ('WRONG_ANSWER', '答案错误'), ('TIME_LIMIT_EXCEEDED', '运行超时'), ('RUNTIME_ERROR', '运行错误'), ('SYSTEM_ERROR', '系统错误'), ('COMPILE_ERROR', '编译错误')], default='PENDING', max_length=30),
        ),
    ]
